# Google Cloud Build configuration for GoTravel
# This file enables automatic deployment from GitHub to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gotravel:$COMMIT_SHA'
      - '.'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/gotravel:$COMMIT_SHA'
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gotravel'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gotravel:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=$$GEMINI_API_KEY,GOOGLE_API_KEY=$$GOOGLE_API_KEY,OPENWEATHERMAP_API_KEY=$$OPENWEATHERMAP_API_KEY'

# Store the built image in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/gotravel:$COMMIT_SHA'

# Timeout for the entire build (default is 10 minutes)
timeout: '1200s'

# Substitutions for environment variables
substitutions:
  _SERVICE_NAME: 'gotravel'
  _REGION: 'us-central1'

# Options for the build
options:
  # Enable more detailed logging
  logging: CLOUD_LOGGING_ONLY
  # Use a machine with more resources for faster builds
  machineType: 'E2_HIGHCPU_8'